#!/bin/bash
set -eou pipefail

if [ -z "${1:-}" ]; then
    echo "usage: $0 <s3-prefix>"
    exit 1
fi

S3_ROOT="$1"
TEMP_DIR=$(mktemp -d)
NPM_PACKAGE_NAME="pulumi-pulumi.tgz"

if [ "${TRAVIS_PUBLISH_PACKAGES:-}" != "true" ]; then
    echo "TRAVIS_PUBLISH_PACKAGES != 'true', not publishing"
    exit 0
fi

yarn --cwd ./sdk/nodejs/bin pack --filename "${TEMP_DIR}/${NPM_PACKAGE_NAME}"

aws s3 cp --acl public-read "${TEMP_DIR}/pulumi-pulumi.tgz" "${S3_ROOT}/nodejs/${NPM_PACKAGE_NAME}"
aws s3 cp --acl public-read "${PULUMI_ROOT}/bin/pulumi" "${S3_ROOT}/bin/"
aws s3 sync --acl public-read "${PULUMI_ROOT}/bin/" "${S3_ROOT}/bin/" --include "pulumi-resource-pulumi-*"
aws s3 sync --acl public-read "${PULUMI_ROOT}/bin/" "${S3_ROOT}/bin/" --include "pulumi-language-*"
